services:
  _defaults:
    public: true
    autowire: true
    bind:
      $bundleConfig: '%huh_multilingual_fields%'

  HeimrichHannot\MultilingualFieldsBundle\:
    resource: '../../{EventListener,Util}/*'
