services:
  _defaults:
    autowire: true

  HeimrichHannot\MultilingualFieldsBundle\:
    resource: '../src/{EventListener,Util}/*'
    autoconfigure: true
    bind:
      $bundleConfig: '%huh_multilingual_fields%'

  HeimrichHannot\MultilingualFieldsBundle\EventListener\DataContainer\:
    resource: '../src/EventListener/DataContainer/*'
    autoconfigure: true
    public: true

  HeimrichHannot\MultilingualFieldsBundle\Multilingual\TableBuilder: ~